# Intro to NumPy, SciPy, and Matplotlib

## Numpy

In [1]:
import numpy as np

### Comparision of Numpy Array and List

In [2]:
x = [2,3,4,6] #usual Python list
y = np.array(x) #numpy array

In [3]:
print(type(x),x)
print(type(y),y)

<class 'list'> [2, 3, 4, 6]
<class 'numpy.ndarray'> [2 3 4 6]


In [4]:
print(x[1:3])

[3, 4]


In [5]:
print(y[1:3]) 

[3 4]


In [6]:
print(x[[0,2]])

TypeError: list indices must be integers or slices, not list

In [7]:
print(y[[0,2]])

[2 4]


In [8]:
print(y[y>3])

[4 6]


In [9]:
print(x * 5)

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [10]:
print(y * 5)

[10 15 20 30]


In [11]:
print(x ** 2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [12]:
print(y ** 2)

[ 4  9 16 36]


In [13]:
matrix = [[1,2,4],[3,1,0]]
nd_array = np.array(matrix)

In [14]:
print(matrix[1][2])

0


In [15]:
print(nd_array[1, 2])

0


In [16]:
print(np.random.rand())

0.37493731407553665


In [17]:
print(np.random.randn())

0.2955722831707411


In [18]:
print(np.random.randn(4))

[ 0.059816   -0.46082397  1.30260184  1.96200824]


In [19]:
print(np.random.randn(4, 5))

[[-2.46003788  0.89135341 -1.14713491 -1.34096672  0.54791307]
 [-0.17436051  1.01946694 -0.12595682  1.41222676 -1.74029575]
 [ 0.81132472 -1.89380222  1.33932638  1.18751632 -1.32864742]
 [ 0.14559509 -1.26415164 -0.63193315 -0.43852112  0.06850322]]


### range() Method in Python and arange() in Numpy

In [20]:
print(np.arange(0, 8, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]


In [21]:
print(np.range(0, 8, 0.1)) #range only works with int

AttributeError: module 'numpy' has no attribute 'range'

In [22]:
list(range(0,8, 1))

[0, 1, 2, 3, 4, 5, 6, 7]

In [25]:
%timeit np.arange(0, 10000)
%timeit range(0, 10000)

11 µs ± 735 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
516 ns ± 46.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## SciPy